apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  namespace: default
spec:
  volumes: 
  - name: sri-vol
    emptyDir: 
      sizeLimit: 10Gi

  containers:

  - image: nginx
    name: nginx-container
    ports:
    - containerPort: 80
    volumeMounts:
    - name: sri-vol
      mountPath: /usr/share/nginx/html
