
apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  namespace: default
spec:
  volumes: 
  - name: vol-1
    persistentVolumeClaim:
      claimName: pod-pvc
  containers:
  - image: nginx
    name: nginx-container
    ports:
    - containerPort: 80
    volumeMounts:
    - name: vol-1
      mountPath: /usr/share/nginx/html