apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
   
  resources: 
    requests: 
      storage: 10Gi
  selector:
    matchLabels: 
      app: nginx
  storageClassName: abc   

