apiVersion: v1
kind: Pod
metadata: 
  name: add-task-pod

spec: 
  containers:
    - name: add-task-container  
      image: srijansharmadocker/my-addtask-app
      ports:
        - containerPort: 8000
      env: 
        - name: CONNECTION_STRING
          value: Driver={ODBC Driver 17 for SQL Server};Server=tcp:b16.database.windows.net,1433;Database=9;Uid=azure;Pwd={Admin@123456};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;