apiVersion: v1
kind: Pod
metadata: 
  name: delete-task-pod

spec: 
  containers:
    - name: delete-task-container  
      image: srijansharmadocker/delete-task-new
      ports:
        - containerPort: 8000
      env: 
        - name: CONNECTION_STRING
          value: Driver={ODBC Driver 17 for SQL Server};Server=tcp:b16.database.windows.net,1433;Database=9;Uid=azure;Pwd={Admin@123456};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;