apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
spec:
  volumes: 
  - name: vol-2
    persistentVolumeClaim:
     claimName: super-pvc
  containers: 
  - image: nginx
    name: nginx-container
    ports: 
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/new
      name: vol-2
