apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-2
  labels:
    app: nginx
spec:
  accessModes: snip
  - ReadWriteMany
  storageClassName: abc
  azureFile: 
    secretName: azure-secret
    shareName: fs-1
  capacity:   
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain 