apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: super-pvc
spec: 
  accessModes: 
  - ReadWriteMany
  resources: 
    requests: 
      storage: 2Gi
  selector:
    matchLabels: 
      app: nginx
  storageClassName: abc