apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployofsri
spec:
  replicas: 6
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec: 
      containers:
      - image: nginx
        name: ng-cont
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata: 
  name: fire-pod
spec:
  containers:
  - image: linuxserver/firefox
    name: fire-cont
    ports:
    - containerPort: 3000
