apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
spec:
  volumes:
  - name: st-vol
    persistentVolumeClaim:
      claimName: st-pvc
  containers:
  - image: nginx
    name: nginx-container
    ports:
    - containerPort: 80
    volumeMounts:
    - name: st-vol
      mountPath: /usr/share/nginx/html


